spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deal?serverTimezone=Asia/Shanghai
    username: chenli
    password: 190014
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml